ProjectManagement/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from API import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'profile-users', views.ProfileUserViewSet)
router.register(r'group', views.GroupViewSet)
router.register(r'permission', views.PermissionViewSet)
router.register(r'project', views.ProjectViewSet)
router.register(r'project-user', views.ProjectUserViewSet)
router.register(r'document', views.DocumentsViewSet)
router.register(r'task', views.TaskViewSet)
router.register(r'task-dependency', views.DependencyViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('project.urls')),
    url(r'^', include('role.urls')),
    url(r'^', include('users.urls')),
    url(r'^', include('task.urls')),
    url(r'^API/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

role/urls.py
from django.conf.urls import url
from role.views import *

urlpatterns = [

    url(
        r'^role/',
        Role.as_view(),
        name='role'),

    url(
        r'^add-role',
        AddRole.as_view(),
        name='add_role'),

    url(
        r'^delete-role/(?P<id>\w+)/$',
        DeleteRole,
        name='delete_role'),

    url(
        r'^update-role/(?P<id>\w+)/$',
        UpdateRole.as_view(),
        name='update_role'),

    url(
        r'^ajax/role/$',
        ViewRole,
        name='view_role'),

]

project/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
#from django.contrib.auth.models import User,Group
from django.db import models
from users.models import ProfileUser

# Create your models here.


class Project(models.Model):
	STATUS = (
		('In Progress', 'In Progress'),
		('Done', 'Done')
		)

	code = models.CharField(primary_key = True, max_length=8, blank=False, unique=True)
	name = models.CharField(max_length = 20, blank=False, unique=True)
	description = models.CharField(max_length=120, blank=True)
	startDate = models.DateField(null=True)
	endDate = models.DateField(null=True)
	status= models.CharField(max_length= 20, choices=STATUS)
	users= models.ManyToManyField(ProfileUser, through='ProjectUser')
	idTeamWorkProject = models.IntegerField(blank=True, null=True)

	def __str__(self):
		return self.name

	def get_startDate(self):
		print("holis")
		formato = "%d-%m-%Y"
		if self.startDate is None:
			return ''

		date_time = self.startDate.strftime(formato)

		return date_time

	def get_endDate(self):
		formato = "%d-%m-%Y"
		if self.endDate is None:
			return ''

		date_time = self.endDate.strftime(formato)

		return date_time

class ProjectUser(models.Model):
	user = models.ForeignKey(ProfileUser)
	project = models.ForeignKey(Project)
	isResponsable = models.BooleanField(default=False)

	def __str__(self):
		return self.project.code


class Documents(models.Model):
	file = models.FileField(upload_to='files/')
	fk_documents_project = models.ForeignKey(Project, on_delete=models.CASCADE)
	description = models.CharField(max_length=64, blank=False)

	def __str__(self):
		return self.fk_documents_project.name

users/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.core.validators import RegexValidator
from role.forms import *

PHONE_VALIDATOR = RegexValidator(
    regex=r'^(0414|0412|0424|0416|0426)\d{7}$',
    message="Formato de teléfono inválido.",
)

class LoginForm(forms.Form):
	class Meta:
		model = User
		fields = ('username','password','email',)

class UserForm(forms.ModelForm):
	first_name = forms.TextInput(attrs={'id':"first_name",
										'type':"text",
										 'class':"validate",
										'autocomplete':'off'})
	last_name= forms.TextInput(attrs={'id':"last_name",
										'type':"text",
										 'class':"validate",
										'autocomplete':'off'})
	username=forms.CharField(required=True)
	phone = forms.CharField(required=False, validators=[PHONE_VALIDATOR],
							widget=forms.TextInput(attrs={
								'placeholder': "Ej:0412xxxxxx",
								'autocomplete': 'off'}
							))
	email = forms.EmailField(required=True,
							 widget= forms.EmailInput(attrs={'id':"email",
							 	'type':"email",
							 	'class':"validate",
								'autocomplete': 'off'}))

	imageProfile = forms.ImageField(required=False)

	project = forms.CharField(required = False, widget = forms.TextInput(attrs = {'type':"text",
	 								'id':"autocomplete",
	 								 'class':"autocomplete"}))
	rol = forms.ModelChoiceField(
        required=True,
        queryset=Group.objects.all()
    )


	class Meta:
		model= User
		fields = ('first_name','last_name','username','email','groups',)

	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email=email).count() != 0:
			msj = "Este correo ya está siendo utilizado"
			self.add_error('email', msj)
		return email

class UpdateUserForm(forms.ModelForm):
	first_name = forms.CharField(required = True,
								 widget= forms.TextInput(attrs={'id':"first_name",
										'type':"text",
										 'class':"validate"}))
	last_name= forms.CharField(required=True,
							   widget= forms.TextInput(attrs={'id':"last_name",
										'type':"text",
										 'class':"validate"}))
	username=forms.CharField(required= False)
	phone = forms.CharField(required=False, validators=[PHONE_VALIDATOR],
							widget=forms.TextInput(attrs={
								'placeholder':"Ej:0412xxxxxx"
							}))
	email = forms.EmailField(required=True,
							 widget= forms.EmailInput(attrs={'id':"email",
										'type':"email",
										 'class':"validate"}))

	project = forms.CharField(required = False, widget=forms.TextInput(attrs={'type': "text",
															'id': "autocomplete",
															'class': "autocomplete"}))

	rol = forms.ModelChoiceField(
        required=True,
        queryset=Group.objects.all()
    )

	class Meta:
		model= User
		fields = ('first_name','last_name','email','groups',)
    #
	# def clean_email(self):
	# 	print("Clean email")
	# 	email = self.cleaned_data.get('email')
	# 	if User.objects.filter(email=email).count() != 0:
	# 		print("dentro del if")
	# 		msj = "Este correo ya está siendo utilizado"
	# 		self.add_error('email', msj)
	# 	return email

class PasswordResetForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('email',)

class FirstSessionForm(forms.ModelForm):
	password2 = forms.CharField(
		label="Repita la Contraseña: ",
		widget=forms.PasswordInput()
		)

	password = forms.CharField(
    	label="Contraseña: ",
    	widget=forms.PasswordInput()
    	)

	class Meta:
		model = User
		fields=['password',]

	def clean(self):
		password = self.cleaned_data.get('password')
		password2 = self.cleaned_data.get('password2')
		lenPass = len(password)

		if password and password != password2:
			msj = "Las contraseñas no coinciden, por favor intente nuevamente."
			self.add_error('password',msj)

		if (lenPass < 8) or (lenPass >= 16 ):
			msj = "La contraseña debe ser mayor a 8 dígitos y menor a 15."
			self.add_error('password2',msj)
		return self.cleaned_data

class UpdateProfileForm(forms.ModelForm):
	first_name = forms.CharField(required=True,
								 widget=forms.TextInput(attrs={'id': "first_name",
															   'type': "text",
															   'class': "validate"}))
	last_name = forms.CharField(required=True,
							   widget=forms.TextInput(attrs={'id': "last_name",
															 'type': "text",
															 'class': "validate"}))
	username=forms.CharField(required= True)
	phone = forms.CharField(required=False)
	image_profile = forms.ImageField(required=False)

	class Meta:
		model= User
		fields = ('first_name','last_name','groups',)

ProjectManagement/templates/base2.html
{% load staticfiles %} 
<!DOCTYPE html>

<html lang="en">
<head>
    {% block head %}
     {% endblock %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
   

    <title>{% block title %}{% endblock title %}</title>

    <!-- Favicons-->
    <link rel="icon" href="../static/images/logotipo_idbc.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="../static/images/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="../static/images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->


    <!-- CORE CSS-->
    <link href="../static/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="../static/css/style.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="http://cdn.datatables.net/1.10.6/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" media="screen,projection">


    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="../static/js/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="../static/css/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="../static/js/plugins/jvectormap/jquery-jvectormap.css" type="text/css" rel="stylesheet" media="screen,projection">
     <link href="../static/js/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet" media="screen,projection">

 </head>

<body>

    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START HEADER -->
    <header id="header" class="page-topbar">
         <!-- start header nav-->
        <div class="navbar-fixed">
            <nav class="background-nav">
                <div class="nav-wrapper">
                    <h1 class="logo-wrapper"><a href="{% url 'project'%}" class="brand-logo darken-1"><img id ="banner" src="../static/images/logotipo_idbc_blanco.png" alt="materialize logo"></a> <span class="logo-text">IDBC Group</span></h1>
                    <ul class="right hide-on-med-and-down">
                        <li class="search-out">
                            <input type="text" class="search-out-text">
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="waves-effect waves-block waves-light show-search"><i class="mdi-action-search"></i></a>
                        </li>


                    </ul>
                </div>
            </nav>
        </div>
         <!-- end header nav-->
    </header>


        {% block content %}
        {% endblock %}

 {% block footer %}
  <!-- START FOOTER -->

  <footer class="page-footer background-nav no-padding">
    <div class="footer-copyright">
      <div class="container">
        <span class ="grey-text text-lighten-4">Copyright © 2017 <a class="grey-text text-lighten-4" target="_blank">IDBC Group</a> All rights reserved.</span>
        <span class="right grey-text text-lighten-4"> Design and Developed by <a class="grey-text text-lighten-4">IDBC Group</a></span>
        </div>
    </div>
  </footer>
  <!-- END FOOTER -->

    {% endblock %}


    <!-- ================================================
    Scripts
    ================================================ -->

    <!-- jQuery Library -->
    <script type="text/javascript" src="../static/js/jquery-1.11.2.min.js"></script>
    <!--materialize js-->
    <script type="text/javascript" src="../static/js/materialize.min.js"></script>
    <script type="text/javascript" src="../static/js/materialize.js"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="../static/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>


    <!-- chartist -->
    <script type="text/javascript" src="../static/js/plugins/chartist-js/chartist.min.js"></script>

    <!-- chartjs -->
    <script type="text/javascript" src="../static/js/plugins/chartjs/chart.min.js"></script>
    <script type="text/javascript" src="../static/js/plugins/chartjs/chart-script.js"></script>

    <!-- data-tables -->
    <script type="text/javascript" src="../static/js/plugins/data-tables/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="../static/js/plugins/data-tables/data-tables-script.js"></script>

    <!-- sparkline -->
    <script type="text/javascript" src="../static/js/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script type="text/javascript" src="../static/js/plugins/sparkline/sparkline-script.js"></script>

    <!--jvectormap-->
    <script type="text/javascript" src="../static/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script type="text/javascript" src="../static/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script type="text/javascript" src="../static/js/plugins/jvectormap/vectormap-script.js"></script>


    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="../static/js/plugins.js"></script>

    {% block script%}
    {% endblock %}


    
</body>

</html>

ProjectManagement/templates/emailEndProject.html
    {% block content %}
        <div>
            <h2> Estimado/a Usuario/a </h2>
            <br>
            <p> La culminación del proyecto {{ project }} está programada para {{ endDate }}.</p>
            <p> Recuerde que debe finalizar las actividades para entonces</p>
            <p> Saludos cordiales.</p>
            <br>
        </div>
    {% endblock %}

ProjectManagement/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


{% endblock %}

{% block content %}

 <!-- Start Page Loading -->
<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<!--Title start-->
<div class=" grey lighten-4">
  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12">
        <h1 class="bold black-text center">Proyectos</h1>
      </div>
    </div>
  </div>
</div>
    {% if perms.project.add_project %}
<div class="row">
    <div class = "col s12 m12 l11">
         <p class="right"><a class="btn-floating btn-large tooltipped waves-effect waves-light deep-purple accent-2 lighten-2" id="new_project"
                         data-position="bottom" data-delay="50" data-tooltip="Nuevo Proyecto" href = "{% url 'new_project' %}"><i class="mdi-content-add"></i></a></p>
    </div>
</div>
    {% endif %}

    <!--Title end-->

<!--Modal-->
 <div class = "modal" id = "modal2">
        <nav class="background-nav-modal">
            <a class="modal-close right"><i class="mdi-navigation-close"></i></a>
            <h3 class = "bold center">Eliminar Proyecto</h3>
        </nav>
        <div class="modal-content">
            <p> ¿Está seguro que desea eliminar este proyecto? </p>
        </div>
        <div class="divider"></div>
        <div class = "modal-footer background-nav-modal">
            <a onclick="kwargsDelete($('#project').text())" class="waves-effect btn-flat modal-action modal-close white-text">Aceptar</a>
            <a href="#" class="waves-effect btn-flat modal-action modal-close white-text">Cancelar</a>
        </div>
    </div>

            <!-- //////////////////////////////////////////////////////////////////////////// -->
       <!--start container-->
        <div class="container">
            <div class="section">
                <div class="section">

                    <div class="row">
                        <div class = "col s10 m10 l12 center">
                            <div id="chart_div"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col s12 m12 l12" id ="detail" style="display: none;">
                    <div class="col s6 m6 l6">
                    </div>
                    <div class="col s4 m4 l12 ">
                        <span class="strong" id="project"></span>
                         <span id ="stat">(<span id="status"></span>)</span>
                        <span>
                            {% if perms.project.delete_project %}
                            <a class="waves-effect waves-light modal-trigger center tooltipped chat-collapse right"
                               data-position="left" data-delay="50" data-tooltip="Eliminar Proyecto" href="#modal2"><i class="mdi-action-highlight-remove prefix icon-project" id="remove"></i></a>
                            {% endif %}
                            {% if perms.project.change_project %}
                            <a onclick="kwargsUpdate($('#project').text())" class="center tooltipped right" id="editProject"
                               data-position="bottom" data-delay="50" data-tooltip="Editar Proyecto">
                                <i class="mdi-content-create prefix icon-project"></i></a>
                            {% endif %}
                            {% if perms.project.view_project%}
                            <a onclick="kwargs($('#project').text())" class="center tooltipped right" id="detailProject"
                               data-position="top" data-delay="50" data-tooltip="Detallar Proyecto" >
                                <i class="mdi-action-visibility prefix icon-project" id="visible"></i></a>
                            {% endif %}
                        </span>
                    </div>
                    <div class="row">
                        <div class="col l1"><p></p></div>
                        <div class="col s12 m12 l5">
                            <p><b>Fecha Inicio: </b><span id ="start"> </span></p>
                            <p><b>Cliente Responsable: </b><span id="client"></span></p>
                        </div>
                        <div class="col s6 m6 l5">

                            <p><b>Fecha de Culminación (Estimada):</b> <span id ="end"></span></p>
                            <p><b>Responsable de la empresa:</b> <span id ="employ"></span></p>
                        </div>
                    </div>
                </div>
            </div>

           {% comment %} <div class="section" id="table_task" style="display: none;">
                <h3 class="header bold"> Tareas</h3>
                <div class="row">
                    <div class="col s12 m12 l12" id = "tabla">
                        <table id="data-table-simple" class="responsive-table display centered striped" cellspacing="0">
                            <thead>
                            <tr id="filas">
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Responsable</th>
                                <th>Fecha de Inicio</th>
                                <th>Fecha Fin (Estimada)</th>
                                <th>Requerida por</th> <!-- la otra tarea necesita de mi -->
                                <th>Requiere de</th> <!-- Necesito de otra tarea -->
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Responsable</th>
                                <th>Fecha de Inicio</th>
                                <th>Fecha Fin (Estimada)</th>
                                <th>Requerida por</th>
                                <th>Requiere de</th>
                                <th>Status</th>
                            </tr>
                            </tfoot>
                            <tbody id="info">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>{% endcomment %}

        <div class="section" id="table_task" style="display: none;">
            <!--DataTables Users-->
            <div id="table-datatables">
                <div class="row">
                    <div class="col s12 m12 l12"  id = "tabla">
                        <h3 class="header bold ">Tareas</h3>
                        <table id="data-table-simple" class="responsive-table display centered striped tableProject" cellspacing="0">

                            <thead>
                             <tr id="filas">
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Responsable</th>
                                <th>Fecha de Inicio</th>
                                <th>Fecha Fin (Estimada)</th>
                                <th>Requerida por</th> <!-- la otra tarea necesita de mi -->
                                <th>Requiere de</th> <!-- Necesito de otra tarea -->
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Responsable</th>
                                <th>Fecha de Inicio</th>
                                <th>Fecha Fin (Estimada)</th>
                                <th>Requerida por</th>
                                <th>Requiere de</th>
                                <th>Status</th>
                            </tr>
                            </tfoot>
                            <tbody id="info">

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
        </div>
      <!-- END CONTENT -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->

{% endblock %}

{% block script%}
    <!--chart google-->
    <script type="text/javascript" src="../static/js/loader.js"></script>
    <script type="text/javascript" src="../static/js/gantt.js"></script>
    <script type="text/javascript" src="../static/js/kwargs.js"></script>


    <script type="text/javascript">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                Materialize.toast('{{ error|escape }}', 4000);
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            Materialize.toast('{{ error|escape }}', 4000);
        {% endfor %}
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            Materialize.toast('{{message}}',4000);
        {% endfor %}
    {% endif %}
</script>
{% endblock %}

ProjectManagement/templates/page-profile.html
{% extends "base.html" %}
{% load static %}


{% block content %}

    <!--Title start-->
    <div class=" grey lighten-4">
      <div class="container">
        <div class="row">
          <div class="col s12 m12 l12">
            <h1 class="bold black-text center">Perfil</h1>
          </div>
        </div>
      </div>
    </div>
    <!--Title end-->

        <!-- //////////////////////////////////////////////////////////////////////////// -->

   <!--start container-->
    <div class="container">
      <div class="section">

        <!--DataTables Users-->
                   <!--New Users-->
              <div class = "row">
                  
                  <div class="col s12 m12 l12">
                      <div class="card-panel">
                          <div class="row">
                            <div class="col s6">
                              <h4 class="header2">Perfil </h4>
                          </div>
                          <div class="col s6 right">
                              <br>
                              <span class="right required-modal"><span class="red-text"> *</span> Denota campo requerido</span>

                          </div>
                          </div>
                          <div class="row">
                              <form  enctype="multipart/form-data"  method="post">
                                  <div class="col s6">
                                  <div class="row">
                                      <div class="input-field col s12">
                                          <i class="mdi-action-account-box prefix"></i>
                                          {{ form.first_name }}
                                          <label for="first_name">Nombre <span class="red-text"> *</span></label>
                                          {% if form.errors %}
                                                <span>
                                                    <strong >{{form.first_name.errors}}</strong>
                                                </span>
                                            {% endif %}
                                      </div>
                                  </div>
                                  <div class="row">
                                      <div class="input-field col s12">
                                          <i class="mdi-action-account-box prefix"></i>
                                          {{ form.last_name }}
                                          <label for="last_name">Apellido <span class="red-text"> *</span></label>
                                          {% if form.errors %}
                                                <span >
                                                    <strong >{{form.last_name.errors}}</strong>
                                                </span>
                                          {% endif %}
                                      </div>
                                  </div>
                                  <div class="row">
                                      <div class="input-field col s12">
                                          <i class="mdi-action-account-circle prefix"></i>
                                          {{ form.username }}
                                          <label for="username">Username <span class="red-text"> *</span></label>
                                          {% if form.errors %}
                                                <span >
                                                    <strong >{{form.username.errors}}</strong>
                                                </span>
                                          {% endif %}
                                      </div>
                                  </div>
                                  <div class="row">
                                      <div class="input-field col s12">
                                          <i class="mdi-social-group prefix"></i>
                                          <input disabled id="email" type="email" class="validate" value="{{user.groups.all.0.name }}">
                                          <label for ="rol" class="active">Rol </label>
                                                                                   
                                      </div>
                                  </div>
                                  <div class="row">
                                      <div class="input-field col s12">
                                          <i class="mdi-communication-email prefix"></i>
                                          <input disabled id="email" type="email" class="validate" value="{{ user.email }}">
                                          <label for="email4" >Email </label>

                                      </div>
                                  </div>

                                  <div class="row">
                                      <div class="input-field col s12">
                                          <i class="mdi-hardware-phone-iphone prefix"></i>
                                          {{ form.phone }}
                                          <label for="phone">Teléfono</label>
                                      </div>
                                  </div>                     
                                      <div class="row ">
                                          <div class="input-field col s12 m6 l6 center">
                                              <a class="btn  deep-purple accent-2 waves-effect waves-light " href="javascript:history.go(-1)">Cancelar
                                                  <i class="mdi-content-reply right"></i>
                                              </a>
                                          </div>
                                          <div class="input-field col s12 m6 l6 center">
                                              <button class="btn  deep-purple accent-2 waves-effect waves-light" type="submit" name="action">Guardar
                                                  <i class="mdi-content-send right"></i>
                                              </button>
                                          </div>
                                      </div>
                                  </div>

                               <div class="col s6 m6 l6 center">
                                   {% csrf_token %}
                                   {% if users.loadPhoto == True %}
                                        <img src="{{ users.imageProfile.url }}" class="circle responsive-img valign profile-image image">
                                   {% else %}
                                       <img src="{% static 'images/avatar1.png' %}" class="circle responsive-img valign profile-image image">
                                   {% endif %}
                                  <div class="row">
                                  <div class="col s3"><p></p></div>
                                  <div class="file-field input-field col s7">
                                  <div class="btn col s4">
                                      <span>Examinar</span>
                                      <input type="file" accept='.jpg, .png, .jpeg' name="image_profile" id="id_image_profile"/>
                                  </div>
                                      <input class="file-path validate " type="text" value="" />
                                  </div>
                                  
                                 </div>
                              </div>
                                  </form>
                          </div>
                      </div>
                  </div>
                 
              </div>
    

      </div>

    </div>
    <!--end container-->


{% endblock %}

{% block script%}

    <script src="../static/js/jquery-ui.js"></script>

    <!-- Others-->
    <script type="text/javascript" src="../static/js/others.js"></script>

    <script type="text/javascript">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    Materialize.toast('{{ error|escape }}', 4000);
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                Materialize.toast('{{ error|escape }}', 4000);
            {% endfor %}
        {% endif %}

        {% if messages %}
            {% for message in messages %}
                Materialize.toast('{{message}}',4000);
            {% endfor %}
        {% endif %}
    </script>
{% endblock %}s

ProjectManagement/templates/password-reset-done.html
{% block content %}
    <h4>Le hemos enviado un correo a la dirección indicada.</h4>
{% endblock %}